version: '3'
services:
  app:
    container_name: Gerapy
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - /volume1/docker/gerapy:/app/gerapy
    ports:
      - 8998:8000
    restart: unless-stopped
